name: NaughtyList
main: gmail.MinecraftMondaysDev.NaughtyList.NaughtyList
version: 0.0.01
author: kpwn243
commands:
   nl:
       description: Add/Remove or check to see if this player is on the naughty list
       usage: /nl add|remove|check Player